version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore
build:
  verbosity: minimal

deploy:
  tag: unstable
  release: Latest Commit
  description: 'This build is updated every time a commit is pushed to master. These builds are unstable!
  Please report bugs in [Issues](https://github.com/ScanMountGoat/SFGraphics/issues).\n\n
  Commit: $(APPVEYOR_REPO_COMMIT)\n\n
  Message: $(APPVEYOR_REPO_COMMIT_MESSAGE)\n\n
  Timestamp: $(APPVEYOR_REPO_COMMIT_TIMESTAMP)'
  provider: GitHub
  auth_token:
    secure: DNTK4wihn5WZAjdhZ+6VBeCglveAy4gO4q5qZ86hhYZ7O26xpQ79XpcK0RyPfPMk
  artifact: SFGraphics.zip
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: master

test:
  assemblies:
    except:
    # Skip tests that require a graphics context.
    - '**\Test Projects\SFGraphics.Test\bin\Release\SFGraphics.Test.dll'
    - '**\Test Projects\SFGenericModel.Test\bin\Release\SFGenericModel.Test.dll'
    - '**\Test Projects\SFShaderLoader.Test\bin\Release\SFShaderLoader.Test.dll'
    - '**\Test Projects\SFGraphics.Controls.Test\bin\Release\SFGraphics.Controls.Test.dll'
    - '**\Test Projects\SFGraphics.ShaderGen.Test\bin\Release\netcoreapp3.1\SFGraphics.ShaderGen.Test.dll'

after_build:
    - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGraphics\bin\Release\netstandard2.0\SFGraphics.dll"
    - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGraphics\bin\Release\netstandard2.0\SFGraphics.xml"
    - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGraphics.Utils\bin\Release\netstandard2.0\SFGraphics.Utils.dll"
    - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGraphics.Utils\bin\Release\netstandard2.0\SFGraphics.Utils.xml"
    - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGenericModel\bin\Release\netstandard2.0\SFGenericModel.dll"
    - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGenericModel\bin\Release\netstandard2.0\SFGenericModel.xml"
    - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGraphics.Controls\bin\Release\netstandard2.0\SFGraphics.Controls.dll"
    - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGraphics.Controls\bin\Release\netstandard2.0\SFGraphics.Controls.xml"
    - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFShapes\bin\Release\netstandard2.0\SFShapes.dll"
    - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFShapes\bin\Release\netstandard2.0\SFShapes.xml"
    - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFShaderLoader\bin\Release\netstandard2.0\SFShaderLoader.dll"
    - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFShaderLoader\bin\Release\netstandard2.0\SFShaderLoader.xml"
    - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGraphics.Timing\bin\Release\netstandard2.0\SFGraphics.Timing.dll"
    - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGraphics.Timing\bin\Release\netstandard2.0\SFGraphics.Timing.xml"
    - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGraphics.ShaderGen\bin\Release\netstandard2.0\SFGraphics.ShaderGen.dll"
    - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGraphics.ShaderGen\bin\Release\netstandard2.0\SFGraphics.ShaderGen.xml"
    - appveyor PushArtifact "SFGraphics.zip"
