version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore
build:
  verbosity: minimal

deploy:
  tag: unstable
  release: Latest Commit
  description: 'This build is updated every time a commit is pushed to master. These builds are unstable!
  Please report bugs in [Issues](https://github.com/ScanMountGoat/SFGraphics/issues).\n\n
  Commit: $(APPVEYOR_REPO_COMMIT)\n\n
  Message: $(APPVEYOR_REPO_COMMIT_MESSAGE)\n\n
  Timestamp: $(APPVEYOR_REPO_COMMIT_TIMESTAMP)'
  provider: GitHub
  auth_token:
    secure: DNTK4wihn5WZAjdhZ+6VBeCglveAy4gO4q5qZ86hhYZ7O26xpQ79XpcK0RyPfPMk
  artifact: SFGraphics.zip
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: master

test:
  assemblies:
    except:
    - '**\Test Projects\SFGraphics.Test.RenderTests\bin\Release\SFGraphics.Test.RenderTests.dll'

after_build:
  - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGraphics\bin\Release\SFGraphics.dll"
  - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGraphics\bin\Release\SFGraphics.xml"
  - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGraphics.Utils\bin\Release\SFGraphics.Utils.dll"
  - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGraphics.Utils\bin\Release\SFGraphics.Utils.xml"
  - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGenericModel\bin\Release\SFGenericModel.dll"
  - 7z a "SFGraphics.zip" "%APPVEYOR_BUILD_FOLDER%\Projects\SFGenericModel\bin\Release\SFGenericModel.xml"
  - appveyor PushArtifact "SFGraphics.zip"
