version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore
build:
  verbosity: minimal
test:
  assemblies:
    except:
    - '**\test\SFGraphicsRenderTests\bin\$(configuration)\SFGraphicsRenderTests.dll'